import { Component } from '@angular/core';
import { IItem } from './interfaces/IItem';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  items: IItem[] = [
    {
      id: 1,
      top: 10,
      left: 10,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 2,
      top: 140,
      left: 10,
      width: 100,
      height: 100,
      text: 'Testando',
    }/* ,
    {
      id: 3,
      top: 260,
      left: 10,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 4,
      top: 380,
      left: 10,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 5,
      top: 500,
      left: 10,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 1,
      top: 10,
      left: 120,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 2,
      top: 140,
      left: 120,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 3,
      top: 260,
      left: 120,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 4,
      top: 380,
      left: 120,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 5,
      top: 500,
      left: 120,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 1,
      top: 10,
      left: 230,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 2,
      top: 140,
      left: 230,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 3,
      top: 260,
      left: 230,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 4,
      top: 380,
      left: 230,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 5,
      top: 500,
      left: 230,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 1,
      top: 10,
      left: 340,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 2,
      top: 140,
      left: 340,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 3,
      top: 260,
      left: 340,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 4,
      top: 380,
      left: 340,
      width: 100,
      height: 100,
      text: 'Testando',
    },
    {
      id: 5,
      top: 500,
      left: 340,
      width: 100,
      height: 100,
      text: 'Testando',
    }, */
  ];
}
